name: Libseccomp-rs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: sudo apt install libseccomp-dev && cargo build --verbose
    - name: Run tests
      run: sudo apt install libseccomp-dev && cargo test --verbose
